[package]
name = "tutorial4-buffer"
version = "0.1.0"
authors = ["Ryan"]
edition = "2018"


[dependencies]
image = "0.23"
winit = "0.22"
cgmath = "0.17"
wgpu = "0.6"
env_logger = "0.7"
log = "0.4"
futures = "0.3"
# NEW!
bytemuck = { version = "1.4", features = [ "derive" ] }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
shaderc = "0.7"

[[bin]]
name = "tutorial4-buffer"
path = "src/main.rs"

[[bin]]
name = "tutorial4-challenge"
path = "src/challenge.rs"